# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [20]:
import numpy as np
x=np.ones((5,5))*6
x[1:-1,1:-1]=0
print(x)

[[6. 6. 6. 6. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 6. 6. 6. 6.]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [10]:
import numpy as np

print("output matrix:")
x = np.zeros((8,8),dtype=int)

x[1::2,::2] = 9
x[::2,1::2] = 9
x[::2,::2]=3
x[1::2,1::2]=3

print(x)

output matrix:
[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [20]:
import numpy as np
print("empty array:\n ")
arr=np.empty((3,4))
print(arr)

print("\n")

print("full array: \n")

farray=np.full((3,3),6)
print(farray)

empty array:
 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


full array: 

[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [26]:
import numpy as np
flist=[0, 12, 45.21 ,34, 99.91]
f=np.array(flist)
print("Expected OutputValues in Fahrenheit degrees :",f)

print("\n")

print("Values in  Centigrade degrees:\n") 

print(5*f/9 - 5*32/9)



Expected OutputValues in Fahrenheit degrees : [ 0.   12.   45.21 34.   99.91]


Values in  Centigrade degrees:

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [31]:
import numpy as np
list1=[1.00000000+0.j ,0.70710678+0.70710678j]
olist=np.array(list1)
print("Expected Output:\n",olist)

print("Real part :\n",olist.real)
print("Imaginary part :\n",olist.imag)

Expected Output:
 [1.        +0.j         0.70710678+0.70710678j]
Real part :
 [1.         0.70710678]
Imaginary part :
 [0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [33]:
import numpy as np
list1=[0 ,10, 20, 40, 60]
list2=[0, 40]
arr1=np.array(list1)
arr2=np.array(list2)
print(np.in1d(arr1,arr2))

[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [34]:
import numpy as np
arr1=np.array([ 0 ,10, 20, 40, 60])
arr2=np.array([10, 30, 40])
print(np.intersect1d(arr1,arr2))

[10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [47]:
import numpy as np
arr1=np.array([10, 10, 20, 20, 30, 30])
print("original 1d array:\n",arr1)
print("\n unique elements:\n",np.unique(arr1))
arr2=np.array([[1,1],[2,3]])
print("\noriginal 2d array:\n\n",arr2)
print("\nUnique elements :",np.unique(arr2))

original 1d array:
 [10 10 20 20 30 30]

 unique elements:
 [10 20 30]

original 2d array:

 [[1 1]
 [2 3]]

Unique elements : [1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [49]:
import numpy as np
arr1=np.array( [ 0 ,10, 20, 40, 60, 80])
arr2=np.array([10, 30, 40, 50, 70])
print(np.setxor1d(arr1,arr2))

[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [59]:
import numpy as np
print(np.all([0,1,2,3]))
print(np.all([0,1,-2,3]))
print(np.all([1,2,3]))
print(np.all([1,-2,-3,4]))
print(np.all([True,False,True]))
print(np.all([True,True]))

False
False
True
True
False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [60]:
import numpy as np
print(np.all([[1,2],[-2,1]]))
print(np.all([[1,0],[-2,1]]))

True
False


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [66]:
import numpy as np
arr=np.array([1, 2, 3, 4])
print(orgarr)

arr2=np.tile(arr, 2)
print("\nRepeating 2 times:\n",arr2)

arr3=np.tile(arr, 3)
print("Repeating 3 times:\n",arr3)

[1 2 3 4]

Repeating 2 times:
 [1 2 3 4 1 2 3 4]
Repeating 3 times:
 [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [70]:
import numpy as np
arr=np.array([1 ,2 ,3, 4, 5, 6])
print("maximum values-",np.argmax(arr))
print("minimum values-",np.argmin(arr))

maximum values- 5
minimum values- 0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [71]:
import numpy as np
a = np.array([1, 2])
b = np.array([4, 5])
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))

a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [75]:
import numpy as np
arr=np.array([[2,5],[4,4]])
print("Original array:\n",arr)
print("Sort along the first axis:")
print(np.sort(arr, axis=0))
print("Sort along the last axis:")
print(np.sort(arr))

Original array:
 [[2 5]
 [4 4]]
Sort along the first axis:
[[2 4]
 [4 5]]
Sort along the last axis:
[[2 5]
 [4 4]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [76]:
import numpy as np
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
print("output:",np.lexsort((first_names, last_names)))

output: [1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [77]:
import numpy as np
arr= np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(arr)
print("Values bigger than 10 =", arr[arr>10])
print("Their indices are ", np.nonzero(arr > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [83]:
import numpy as np
n = np.zeros((4,4))
print("%d bytes" %(n.size * n.itemsize))

128 bytes


## Great Job!